export const START_QUIZ = 'Start Quiz';
export const ADD_CARD = 'Add Card';
export const CARDS = 'Cards';
export const QUESTION = 'Question';
export const ANSWER = 'Answer';
export const NEW_DECK_TITLE = 'What is the title of your new deck?';
export const SUBMIT = 'Submit';
export const QUIZ = 'Quiz';
export const NO_CARDS = 'This Deck has not cards, please add cards';
export const CORRECT = 'Correct';
export const INCORRECT = 'Incorrect';
export const QUIZ_FINISHED = 'Quiz Finished';
export const CORRECT_ANSWERS = 'Your correct answers were';
export const RESTART_QUIZ = 'Restart Quiz';
export const BACK_DECK = 'Back to Deck';
export const NO_DECKS = 'There are not Decks';
export const ADD_DECK = 'Add Deck';

export const NOTIFICATION_KEY = 'flashcards:notifications'
